# one highlight of juxtaposition, the ease of use with
# community creation
communities:
  
  # it's this easy
  -

    # community name
    name: "general"

    # icon
    icon: None

    # is it pinned
    pinned: True

    # banner
    banner: None

    # permission levels
    permissions:

      # minimum permission level required
      # to have moderation perms
      moderate: 2

      # minimum permission level required
      # to post
      post: 3

      # minimum permission level required
      # to comment
      comment: 3

      # minimum permission level required
      # to view posts
      view: 4

  # the announcements community
  -

    # community name
    name: "announcements"

    # icon
    icon: None

    # is it pinned
    pinned: True

    # banner
    banner: None

    # permission levels
    permissions:

      # minimum permission level required
      # to have moderation perms
      moderate: 2

      # minimum permission level required
      # to post
      post: 2

      # minimum permission level required
      # to comment
      comment: 2

      # minimum permission level required
      # to view posts
      view: 4